name: Broken link check workflow
on: [workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    outputs:
      output2: ${{ steps.step2.outputs.test }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Scan for broken links
      id: step2
      uses: enkeyz/linkcheck@test_release
